-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 14:29:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `sub` VARCHAR(128) NOT NULL,
  `username` VARCHAR(16) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sub`));


-- -----------------------------------------------------
-- Table `mydb`.`family_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`family_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`family_info` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `user_sub` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`, `user_sub`),
  INDEX `fk_family_info_user1_idx` (`user_sub` ASC) VISIBLE,
  CONSTRAINT `fk_family_info_user1`
    FOREIGN KEY (`user_sub`)
    REFERENCES `mydb`.`user` (`sub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccination_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vaccination_list` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vaccination_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BCG` TINYINT NULL,
  `HEpB_1` TINYINT NULL,
  `HepB_2` TINYINT NULL,
  `HepB_3` TINYINT NULL,
  `DTaP_1` TINYINT NULL,
  `DTaP_2` TINYINT NULL,
  `DTaP_3` TINYINT NULL,
  `DTaP_4` TINYINT NULL,
  `DTaP_5` TINYINT NULL,
  `Tdap/Td` TINYINT NULL,
  `IPV_1` TINYINT NULL,
  `IPV_2` TINYINT NULL,
  `IPV_3` TINYINT NULL,
  `IPV_4` TINYINT NULL,
  `Hib_1` TINYINT NULL,
  `Hib_2` TINYINT NULL,
  `Hib_3` TINYINT NULL,
  `Hib_4` TINYINT NULL,
  `PCV_1` TINYINT NULL,
  `PCV_2` TINYINT NULL,
  `PCV_3` TINYINT NULL,
  `PCV_4` TINYINT NULL,
  `PPSV` TINYINT NULL,
  `MMR_1` TINYINT NULL,
  `MMR_2` TINYINT NULL,
  `VAR` TINYINT NULL,
  `HepA_1` TINYINT NULL,
  `HepA_2` TINYINT NULL,
  `IJEV_1` TINYINT NULL,
  `IJEV_2` TINYINT NULL,
  `IJEV_3` TINYINT NULL,
  `IJEV_4` TINYINT NULL,
  `IJEV_5` TINYINT NULL,
  `LJEV_1` TINYINT NULL,
  `LJEV_2` TINYINT NULL,
  `HPV_1` TINYINT NULL,
  `HPV_2` TINYINT NULL,
  `IIV` TINYINT NULL,
  `RV1_1` TINYINT NULL,
  `RV1_2` TINYINT NULL,
  `RV5_1` TINYINT NULL,
  `RV5_2` TINYINT NULL,
  `RV5_3` TINYINT NULL,
  `family_info_id` INT NOT NULL,
  PRIMARY KEY (`id`, `family_info_id`),
  INDEX `fk_vaccination_list_family_info1_idx` (`family_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_vaccination_list_family_info1`
    FOREIGN KEY (`family_info_id`)
    REFERENCES `mydb`.`family_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hospital` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `rating_mean` VARCHAR(45) NULL,
  `vaccine_list` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NULL,
  `rating` INT NULL,
  `creating_date` DATETIME NULL,
  `user_id1` VARCHAR(45) NOT NULL,
  `user_sub` VARCHAR(128) NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_sub`, `hospital_id`),
  INDEX `fk_comment_user1_idx` (`user_sub` ASC) VISIBLE,
  INDEX `fk_comment_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_sub`)
    REFERENCES `mydb`.`user` (`sub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccination_list_copy1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vaccination_list_copy1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vaccination_list_copy1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BCG` TINYINT NULL,
  `HEpB_1` TINYINT NULL,
  `HepB_2` TINYINT NULL,
  `HepB_3` TINYINT NULL,
  `DTaP_1` TINYINT NULL,
  `DTaP_2` TINYINT NULL,
  `DTaP_3` TINYINT NULL,
  `DTaP_4` TINYINT NULL,
  `DTaP_5` TINYINT NULL,
  `Tdap/Td` TINYINT NULL,
  `IPV_1` TINYINT NULL,
  `IPV_2` TINYINT NULL,
  `IPV_3` TINYINT NULL,
  `IPV_4` TINYINT NULL,
  `Hib_1` TINYINT NULL,
  `Hib_2` TINYINT NULL,
  `Hib_3` TINYINT NULL,
  `Hib_4` TINYINT NULL,
  `PCV_1` TINYINT NULL,
  `PCV_2` TINYINT NULL,
  `PCV_3` TINYINT NULL,
  `PCV_4` TINYINT NULL,
  `PPSV` TINYINT NULL,
  `MMR_1` TINYINT NULL,
  `MMR_2` TINYINT NULL,
  `VAR` TINYINT NULL,
  `HepA_1` TINYINT NULL,
  `HepA_2` TINYINT NULL,
  `IJEV_1` TINYINT NULL,
  `IJEV_2` TINYINT NULL,
  `IJEV_3` TINYINT NULL,
  `IJEV_4` TINYINT NULL,
  `IJEV_5` TINYINT NULL,
  `LJEV_1` TINYINT NULL,
  `LJEV_2` TINYINT NULL,
  `HPV_1` TINYINT NULL,
  `HPV_2` TINYINT NULL,
  `IIV` TINYINT NULL,
  `RV1_1` TINYINT NULL,
  `RV1_2` TINYINT NULL,
  `RV5_1` TINYINT NULL,
  `RV5_2` TINYINT NULL,
  `RV5_3` TINYINT NULL,
  `user_sub` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`, `user_sub`),
  INDEX `fk_vaccination_list_copy1_user1_idx` (`user_sub` ASC) VISIBLE,
  CONSTRAINT `fk_vaccination_list_copy1_user1`
    FOREIGN KEY (`user_sub`)
    REFERENCES `mydb`.`user` (`sub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
