-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 20:31:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mymedi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mymedi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mymedi` DEFAULT CHARACTER SET utf8 ;
USE `mymedi` ;

-- -----------------------------------------------------
-- Table `mymedi`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`user_info` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub` VARCHAR(128) NOT NULL,
  `username` VARCHAR(16) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `birthday` DATE NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sub_UNIQUE` (`sub` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mymedi`.`family_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`family_info` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`family_info` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `relationship_with_user` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `user_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_family_info_user_info1_idx` (`user_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_family_info_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `mymedi`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymedi`.`hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`hospital` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`hospital` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `rating_mean` VARCHAR(45) NULL,
  `vaccine_list` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymedi`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`comment` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NULL,
  `rating` INT NULL,
  `creating_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_info_id` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user_info1_idx` (`user_info_id` ASC) VISIBLE,
  INDEX `fk_comment_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `mymedi`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mymedi`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymedi`.`vaccine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vaccine`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vaccine` (
  `id` int NOT NULL AUTO_INCREMENT,
  `korean` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `vietnam` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `english` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `name` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `vaccine` WRITE;
/*!40000 ALTER TABLE `vaccine` DISABLE KEYS */;
INSERT INTO `vaccine` VALUES (1,'결핵','bệnh lao','tuberculosis','BCG'),(2,'B형간염','viêm gan B','Hepatitis B','HepB'),(3,'디프테리아/파상풍/백일해','bạch hầu / uốn ván /  ho gà.','Tetanus/ Diphtheria/ Pertussis','DTaP/Tdap/Td'),(4,'폴리오','Bại Liệt','Polio','IPV'),(5,'b형 헤모필루스인플루엔자','Haemophilus Influenzae Tuýp b\n','Haemophilus influenzae type B','Hib'),(6,'폐렴구균','phế cầu Viêm phổi','pneumococcus','PCV/ PPSV'),(7,'홍역/유행성이하선염/풍진','bệnh sởi/ quai bị/bệnh ban đào','Measles/ Mumps / Rubella','MMR'),(8,'수두',' thủy đậu ','varicella','VAR'),(9,'A형 간염','viêm gan A','Hepatitis A','HepA'),(10,'일본뇌염','Viêm não Nhật Bản','Japanese encephalitis','IJEV/ LJEV'),(11,'사람유두종바이러스 감염증','Virus gây u nhú ở người','Human papilloma virus infection','HPV'),(12,'인플루엔자','Bệnh Cúm','influenza','IIV'),(13,'로타바이러스 감염증','lây truyền rota virus','rota virus infection','RV1/ RV5');
/*!40000 ALTER TABLE `vaccine` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `mymedi`.`get_vaccine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`get_vaccine` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`get_vaccine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `get_vaccine` TINYINT NULL DEFAULT 1,
  `get_date` DATETIME NULL,
  `family_info_id` INT NULL,
  `user_info_id` INT NULL,
  `vaccine_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_get_vaccine_family_info1_idx` (`family_info_id` ASC) VISIBLE,
  INDEX `fk_get_vaccine_user_info1_idx` (`user_info_id` ASC) VISIBLE,
  INDEX `fk_get_vaccine_vaccine1_idx` (`vaccine_id` ASC) VISIBLE,
  CONSTRAINT `fk_get_vaccine_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `mymedi`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_get_vaccine_vaccine1`
    FOREIGN KEY (`vaccine_id`)
    REFERENCES `mymedi`.`vaccine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymedi`.`vaccine_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymedi`.`vaccine_list` ;

CREATE TABLE IF NOT EXISTS `mymedi`.`vaccine_list` (
  `id` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  `vaccine_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaccine_list_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `fk_vaccine_list_vaccine1_idx` (`vaccine_id` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_list_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mymedi`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_list_vaccine1`
    FOREIGN KEY (`vaccine_id`)
    REFERENCES `mymedi`.`vaccine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
